### ISSUE TITLE
Add support for Perseverence

### ISSUE THREAD

**Issue by pranavsastry** [chrisccerami/mars-photo-api#125] opened 2021-02-18 21:34 UTC
Now that Perseverence has landed on Mars (yay, go NASA), please add support for Perseverence so that we can access the images taken by Perseverence!

**Comment by chrisccerami** [comment] 2021-02-19 00:29
Duplicate of https://github.com/chrisccerami/mars-photo-api/issues/103

**Closed by chrisccerami** 2021-02-19 00:29 UTC
